herefactorizar url
martagrana/Gestion-ciudades pull request #1
Opened 2024-01-13 10:51 UTC by martagrana

He cambiado el service añadiendo una constante url

2024-01-13 16:14 UTC, jdell requested changes
En principio está bien. Puedes hacer el merge en cuanto resuelvas los cambios que te propongo.

2024-01-13 16:14 UTC, jdell commented on ciudades/src/services/city.service.ts
> +  url: string = 'https://capi-papi.azurewebsites.net/userapis/martatech/cities';
La variable `url` podría ser marcada como de solo-lectura utlizando el modificardor `readonly` (mas info [aqui](https://www.tutorialsteacher.com/typescript/typescript-readonly)). Ejemplo:
```
readonly url: string = 'https://capi-papi.azurewebsites.net/userapis/martatech/cities';
```

2024-01-16 10:36 UTC, martagrana commented on ciudades/src/services/city.service.ts
> +  url: string = 'https://capi-papi.azurewebsites.net/userapis/martatech/cities';
He marcado la variable url con el modificador readonly

2024-01-16 10:42 UTC, jdell commented on ciudades/src/services/city.service.ts
> +  url: string = 'https://capi-papi.azurewebsites.net/userapis/martatech/cities';
Perfecto. PR aprobado. Puedes hacer el _merge_ cuando quieras.

2024-01-16 10:42 UTC, jdell approved these changes

2024-01-16 10:46 UTC, merged